FROM phusion/centos-5-32
MAINTAINER The ManyLinux project

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV PATH /opt/rh/devtoolset-2/root/usr/bin:$PATH
ENV LD_LIBRARY_PATH /opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib

COPY ./build_scripts /build_scripts
RUN linux32 bash build_scripts/build.sh && rm -r build_scripts
