FROM centos:5
MAINTAINER The ManyLinux project

ENV AUDITWHEEL_PLAT manylinux1_x86_64

COPY build_scripts /build_scripts
COPY sources /
RUN bash /build_scripts/build.sh && rm -r /build_scripts

ENV SSL_CERT_FILE=/opt/_internal/certs.pem

CMD ["/bin/bash"]
