FROM i386/centos:6


# Centos 6 is EOL and is no longer available from the usual mirrors, so switch
# to https://vault.centos.org
RUN sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/fastestmirror.conf && \
    sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/*.repo && \
    sed -i 's;^#baseurl=http://mirror;baseurl=https://vault;g' /etc/yum.repos.d/*.repo

RUN echo "i386" > /etc/yum/vars/basearch
RUN yum -y update && \
    yum install -y util-linux-ng
COPY ./build_scripts /build_scripts
RUN linux32 bash /build_scripts/rebuild-glibc-without-vsyscall.sh
