name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "tests/**"
      - "*.sh"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "docker/**"
      - "tests/**"
      - "*.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  pre_commit:
    name: Pre-commit checks
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0

  build_matrix:
    name: Build matrix
    needs: pre_commit
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      environment: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'pypa/manylinux') && 'quay.io' || '' }}
    steps:
      - id: matrix
        name: build matrix
        shell: python
        run: |
          import os
          import json
          reduced = [
              ("x86_64", "ubuntu-24.04", ("manylinux2014", "manylinux_2_28", "manylinux_2_34", "musllinux_1_2")),
              ("aarch64", "ubuntu-24.04-arm", ("manylinux2014", "manylinux_2_28", "manylinux_2_34", "manylinux_2_39", "musllinux_1_2")),
              ("i686", "ubuntu-24.04", ("manylinux2014", "manylinux_2_28", "manylinux_2_34", "musllinux_1_2")),
              ("armv7l", "ubuntu-24.04-arm", ("manylinux_2_31", "manylinux_2_35", "musllinux_1_2")),
              ("ppc64le", "ubuntu-24.04", ("manylinux2014", "manylinux_2_28", "manylinux_2_34", "musllinux_1_2")),
              # ("loongarch64", "ubuntu-24.04", ("manylinux_2_38", "musllinux_1_2")),
              ("riscv64", "ubuntu-24.04", ("manylinux_2_39", "musllinux_1_2")),
              ("s390x", "ubuntu-24.04", ("manylinux2014", "manylinux_2_28", "manylinux_2_34", "musllinux_1_2")),
          ]
          expanded = [{"policy": policy, "platform": platform, "runner": runner} for platform, runner, policies in reduced for policy in policies]
          print(json.dumps(expanded, indent=2))
          with open(os.environ["GITHUB_OUTPUT"], "at") as f:
              f.write(f"matrix={json.dumps(expanded)}")

  build_manylinux:
    name: ${{ matrix.policy }}_${{ matrix.platform }}
    needs: build_matrix
    runs-on: ${{ matrix.runner }}
    environment: ${{ needs.build_matrix.outputs.environment }}
    permissions:
      packages: write  # needed to write image cache
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    env:
      POLICY: ${{ matrix.policy }}
      PLATFORM: ${{ matrix.platform }}
      COMMIT_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 50
          persist-credentials: false

      - name: Set up QEMU
        if: matrix.platform == 'loongarch64' || matrix.platform == 'ppc64le' || matrix.platform == 'riscv64' || matrix.platform == 's390x'
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'pypa/manylinux'
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ./build.sh

      - name: Deploy
        if: needs.build_matrix.outputs.environment == 'quay.io'
        run: ./deploy.sh
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  all_passed:
    if: always()
    name: Check all builds passed
    needs: [build_manylinux]
    runs-on: ubuntu-slim
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          jobs: ${{ toJSON(needs) }}

  deploy_multiarch:
    if: needs.build_matrix.outputs.environment == 'quay.io'
    name: Deploy multi-arch images
    needs: [build_matrix, all_passed]
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: quay.io
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install ORAS
        uses: oras-project/setup-oras@1d808f7d7f6995cc68b7bf507bfe5c5446e1dc9d # v2.0.1
      - name: Deploy
        run: ./deploy_multiarch.sh
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
